name: Deploy Documentation preview for PRs

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        if: github.event.action != 'closed' # Skip the build if the PR has been closed
        run: npm i

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./docs/
          umbrella-dir: docs/pr-preview
          preview-branch: gh-pages
          action: deploy

      - name: Delete preview
        uses: rossjrw/pr-preview-action@v1
        if: github.event.action == "closed" && !github.event.pull_request.merged
        with:
          source-dir: ./docs/
          umbrella-dir: docs/pr-preview
          preview-branch: gh-pages
          action: remove