name: Black Linter (PY)

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'components/**'
      - 'infrastructure/**'
      - 'settings/**'
      - 'tests/**'
      - 'manage.py'
  pull_request:
    paths:
      - 'backend/**'
      - 'components/**'
      - 'infrastructure/**'
      - 'settings/**'
      - 'tests/**'
      - 'manage.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
