name: CI Tests

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up environment variables
        run: cp .env.sample .env

      - name: Install MariaDB Connector/C
        run: |
          wget https://downloads.mariadb.com/Connectors/c/connector-c-3.2.4/mariadb-connector-c-3.2.4-linux-x86_64.tar.gz
          tar -xf mariadb-connector-c-3.2.4-linux-x86_64.tar.gz
          sudo mv mariadb-connector-c-3.2.4-linux-x86_64 /usr/local/mariadb-connector-c
          echo "/usr/local/mariadb-connector-c/lib" | sudo tee /etc/ld.so.conf.d/mariadb-connector-c.conf
          sudo ldconfig

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4

      - name: Build and run docker-compose.ci.yml
        run: docker-compose -f infrastructure/backend/docker-compose.ci.yml up -d

      - name: Run the test scripts
        run: |
          docker-compose -f infrastructure/backend/docker-compose.ci.yml exec -T myfinances_django ./infrastructure/backend/scripts/tests/views.sh
